services:
  database:
    image: alexg12/mick-gooding-website-database:${DOCKER_TAG:-latest}
    build: ./database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  database-backup:
    image: prodrigestivill/postgres-backup-local
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    volumes:
      - /var/opt/db_backups:/backups
    restart: always

  backend:
    image: alexg12/mick-gooding-website-backend:${DOCKER_TAG:-latest}
    build: ./api
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_CLIENT_MODE=${PAYPAL_CLIENT_MODE}
      - ENVIRONMENT=prod
    expose:
      - 5000
    restart: always
  
  frontend:
    image: alexg12/mick-gooding-website-frontend:${DOCKER_TAG:-latest}
    build: ./ui
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ${SSL_CERT_PATH}
        target: /etc/nginx/certs/mgw_ssl_certificate.cer
      - type: bind
        source: ${SSL_PRIVATE_KEY_PATH}
        target: /etc/nginx/private/mgw_ssl_private_key.key
      - type: bind
        source: ./certbot-www
        target: /var/www/certbot
    restart: always

volumes:
  pgdata:
