services:
  database:
    build: ./database
    image: alexg12/mick-gooding-website-database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432

  backend:
    build: ./api
    image: alexg12/mick-gooding-website-backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_CLIENT_MODE=${PAYPAL_CLIENT_MODE}
    ports:
    - 5000:5000
    volumes:
      - ./api:/app
  
  frontend:
    build: ./ui
    image: alexg12/mick-gooding-website-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app
    