name: Deploy Staging

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Deploy to staging server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          script: |
            cd mick-gooding-website
            export DOCKER_TAG=main
            docker compose -f compose-prod.yml pull
            docker compose -f compose-prod.yml down
            docker compose -f compose-prod.yml --env-file .env up -d --force-recreate
            unset DOCKER_TAG
