name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ${{ secrets.DOCKERHUB_USERNAME }}/mick-gooding-website-database
            dockerfile: ./database/Dockerfile
          - image: ${{ secrets.DOCKERHUB_USERNAME }}/mick-gooding-website-backend
            dockerfile: ./api/Dockerfile
          - image: ${{ secrets.DOCKERHUB_USERNAME }}/mick-gooding-website-frontend
            dockerfile: ./ui/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
