name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./compose-dev.yml
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build Docker images
        run: docker compose build
      - 
        name: Run API tests
        run: docker compose run backend pytest
